name: CI Kalunga
on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code verification
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_CI }}
